// STRING ARE THE CHARACTER ARRAY WHICH STORE THE CHARACTER IN AN ARRAY AND TO END THE CHARACTER ARRAY OR STRING WE NEED THE NULL CHARACTER OR TERMINATOR WHICH IS  ' /0 '  HAS ASCII VALUE OF 0 




// MAKING A STRING 
#include<iostream>
using namespace std ;

int main(){


  // string decleration 
  char string1[20];
  cout<<"Enter the character in the string : "<<endl;
  cin>>string1;

  cout<<"string enetred is : "<<string1<<endl;
    return 0;
}   // we print the kartik pant   this will print kartik cuz beacuse the space tab and enter is considered as the null character 



//  use case of null character 

// char null_char[5]='k','a','r,'t','i','k','/0';